config/routes.rb
Rails.application.routes.draw do

  root                   'sessions#new'

  get 'login'         => 'sessions#new'

  post 'login'        => 'sessions#create'

  delete 'logout'     => 'sessions#destroy'

  get 'signup'        => 'user#new'

  get 'notes' => 'notes#index'
  
  resources :notes, :users

  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/note.rb
class Note < ActiveRecord::Base
  mount_uploader :data, DataUploader # Tells rails to use this uploader for this model.
  validates :name, presence:true
  validates :composer, presence:true

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :password, presence: true, length: {minimum: 6}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :force_login

  def index
    @notes = Note.all
  end

  def new
    @note = Note.new
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])

    if @note.save
      redirect_to notes_path, notice: "Nodeark redigeret"
    else
      render "edit"
    end
  end

  def create
    @note = Note.new(note_params)

    if @note.save
      redirect_to notes_path, notice: "Noderne til #{@note.name} er blevet gemt"
    else
      render "new"
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to notes_path, notice: "Noderne til #{@note.name} er blevet slettet"
  end

  private

  def note_params
    params.require(:note).permit(:data, :name, :composer, :canview, :arrenged_by, :text_by, :published_by, :notes)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])


    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to notes_path

    else
      flash.now[:danger] = 'Forkert brugernavn/password kombination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :force_admin

  def new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


  #Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  #Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  #Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  #Returns true iff an account is logged it
  def logged_in?
    !current_user.nil?
  end

  #Returns true iff the admin user (UID 2) is logged in. 
  #If your admin user is not user 2 change the code below
  def admin?
    current_user && (current_user.id == 2)
  end

  def force_login
    unless logged_in?
      redirect_to root_path
    end
  end

  def force_admin
    unless admin?
      redirect_to root_path
    end
  end


end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kknoder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 </div class="container" style="padding-top:20px;">
    <% if logged_in? %>
      <li><%= link_to "Log out", logout_path, method: "delete" , class: "btn btn-primary" %>
      <% if admin? %>
      
      <%= link_to "Rediger bruger-password", logout_path, method: "delete" , class: "btn btn-default" %>

      <%= link_to "Rediger administrator-password", logout_path, method: "delete" , class: "btn btn-default" %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/notes/_note_form.html.erb
<div class="well">
  <%= form_for @note, html: { multipart: true } do |f| %>
    <%= f.label "Titel" %>
    <%= f.text_field :name %>
    <br>
    <%= f.label "Fil" %>
    <%= f.file_field :data %>

    <br>
    <%= f.label "Komponist" %>
    <%= f.text_field :composer %>

    <%= f.label "Arrangør" %>
    <%= f.text_field :arrenged_by%>
    <br>

    <%= f.label "Tekst forfatter" %>
    <%= f.text_field :text_by %>
    
    <%= f.label "Udgiver" %>
    <%= f.text_field :published_by %>
    <br>

    <%= f.label "Notater" %>
    <%= f.text_area :notes %>

    <%= f.label "Synlig for bruger" %>
    <%= f.check_box :canview %>
    <br>

    <%= f.submit "Gem", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/notes/edit.html.erb
<h1>Rediger nodeark</h1>

<%= render 'note_form' %>

app/views/notes/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>
<br/>
<%if admin? %>
  <%= link_to "Nyt nodeark", new_note_path, class:"btn btn-primary" %>
<% end %>
<br/><br/>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Titel</th>
      <th>Komponist</th>
      <th>Arrangør</th>
      <th>Tekst forfatter</th>
      <th>Udgiver</th>
      <th>Sidst vist</th>
      <th>Notater</th>
      <th>Download link</th>
      <% if admin? %>      
        <th>Synlig?</th>
        <th> </th>
        <th> </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
      <% if note.canview || admin? %>
      <tr>
        <td><%= note.name%></td>
        <td><%= note.composer %></td>
        <td><%= note.arrenged_by %></td>
        <td><%= note.text_by %></td>
        <td><%= note.published_by %></td>
        <td><%= note.updated_at %></td>
        <td><%= note.notes %></td>
        <td><%= link_to "Download Nodeark", note.data_url %></td>
        <% if admin? %>
          <td> <%= note.canview ? "synlig" : "skjult" %></td>
          <td> <%= link_to "Rediger", edit_note_path(note) %></td>
          <td><%= button_to "Slet",  note, method: :delete, class: "btn btn-danger", confirm: "Er du sikker på at du vil slette #{note.name}?" %></td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/notes/new.html.erb
<% if !@note.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'note_form' %>

app/views/notes/update.html.erb
<h1>Notes#update</h1>
<p>Find me in app/views/notes/update.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>